# For development
version: '2'

services:
  booking-db:
    image: postgres
    restart: always
    container_name: booking-db
    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5439:5432