# уровень логирования для запуска в режиме отладки
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

spring:
  application:
    name: booking

  cloud:
    stream:
      bindings:
        output-user-stats:
          destination: user-statistics
          content-type: application/json
        output-booking-stats:
          destination: booking-statistics
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5439/hotel_booking}
    username: ${USER_DB:postgres}
    password: ${PASS_DB:postgres}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  error:
    include-message: always
  port: 8080